ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += bbry_flash.o
obj-$(CONFIG_MSMB_CAMERA) += bbry_flash_gpio.o
obj-$(CONFIG_MSMB_CAMERA) += pmi8994_flash.o
obj-$(CONFIG_MSMB_CAMERA) += max77387_flash.o
