obj-y += focaltech_core.o 
obj-y += focaltech_ctl.o 
obj-y += focaltech_ex_fun.o 
obj-y += focaltech_gesture.o 
obj-y += focaltech_flash.o

obj-y += focaltech_ex_fun.o



extlibs:=$(PWD)/drivers/input/touchscreen/ft_gesture_32bit_lib_v1.0_20140820.a
#ldflagobj-y += fts_ts.o
obj-y s-y +=--whole-archive $(extlibs) --no-whole-archive

 
